##Este script es para dibujar la figura de RCAs después de correr el script hwmidlevelplot##

print(e1, split = c(1, 1, 4, 5), more = TRUE)
print(f1, split = c(2, 1, 4, 5), more = TRUE)
print(g1, split = c(3, 1, 4, 5), more = TRUE)
print(h1, split = c(4, 1, 4, 5), more = TRUE)
print(ñ1, split = c(1, 2, 4, 5), more = TRUE)
print(o1, split = c(2, 2, 4, 5), more = TRUE)
print(p1, split = c(3, 2, 4, 5), more = TRUE)
print(q1, split = c(4, 2, 4, 5), more = TRUE)
print(v1, split = c(1, 3, 4, 5), more = TRUE)
print(w1, split = c(2, 3, 4, 5), more = TRUE)
print(x1, split = c(3, 3, 4, 5), more = TRUE)
print(y1, split = c(4, 3, 4, 5), more = TRUE)
print(hh1, split = c(1, 4, 4, 5), more = TRUE)
print(ii1, split = c(2, 4, 4, 5), more = TRUE)
print(jj1, split = c(3, 4, 4, 5), more = TRUE)
print(kk1, split = c(4, 4, 4, 5), more = TRUE)
print(ll1, split = c(3, 5, 4, 5), more = TRUE)
print(mm1, split = c(4, 5, 4, 5), more = FALSE)